/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora.gui;

import calculadora.Servidor;
import calculadora.tcp.ServidorTcp;
import calculadora.udp.ServidorUdp;

/**
 *
 * @author udesc
 */
public class Inicial extends javax.swing.JFrame {

    /**
     * Creates new form Inicial
     */
    public Inicial() {
        initComponents();
        this.radioTcp.setSelected(true);
        this.radioCliente.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupProtocolo = new javax.swing.ButtonGroup();
        groupModo = new javax.swing.ButtonGroup();
        txtHost = new javax.swing.JTextField();
        radioTcp = new javax.swing.JRadioButton();
        radioUdp = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        btnCancela = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        radioServidor = new javax.swing.JRadioButton();
        radioCliente = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtHost.setText("localhost");
        txtHost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHostActionPerformed(evt);
            }
        });

        groupProtocolo.add(radioTcp);
        radioTcp.setText("Tcp");
        radioTcp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioTcpActionPerformed(evt);
            }
        });

        groupProtocolo.add(radioUdp);
        radioUdp.setText("Udp");
        radioUdp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioUdpActionPerformed(evt);
            }
        });

        jLabel1.setText("Endereço");

        jLabel2.setText("Protocolo");

        btnOk.setText("ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnCancela.setText("Cancelar");
        btnCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelaActionPerformed(evt);
            }
        });

        jLabel3.setText("Modo");

        groupModo.add(radioServidor);
        radioServidor.setText("Servidor");
        radioServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioServidorActionPerformed(evt);
            }
        });

        groupModo.add(radioCliente);
        radioCliente.setText("Cliente");
        radioCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(btnCancela)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnOk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHost))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioTcp)
                            .addComponent(radioServidor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioUdp)
                            .addComponent(radioCliente))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(radioTcp)
                        .addComponent(radioUdp))
                    .addComponent(jLabel2))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(radioServidor)
                        .addComponent(radioCliente)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk)
                    .addComponent(btnCancela))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHostActionPerformed

    private void radioTcpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioTcpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioTcpActionPerformed

    private void radioUdpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioUdpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioUdpActionPerformed

    private void btnCancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelaActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelaActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        int tcp = 0;
        if(radioTcp.isSelected()){
            tcp = 1;
        }
        if(radioCliente.isSelected()){
            Interface janela = new Interface(this.txtHost.getText(), tcp);
            janela.setVisible(true);
        }else{
            Servidor servidor;
            if(tcp == 1){
                servidor = new ServidorTcp(this.txtHost.getText());
            }else{
                servidor = new ServidorUdp(this.txtHost.getText());
            }
            
            Thread tmpThread = new Thread(servidor);
            tmpThread.start();
        }
        this.setVisible(false);
    }//GEN-LAST:event_btnOkActionPerformed

    private void radioServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioServidorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioServidorActionPerformed

    private void radioClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioClienteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancela;
    private javax.swing.JButton btnOk;
    private javax.swing.ButtonGroup groupModo;
    private javax.swing.ButtonGroup groupProtocolo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton radioCliente;
    private javax.swing.JRadioButton radioServidor;
    private javax.swing.JRadioButton radioTcp;
    private javax.swing.JRadioButton radioUdp;
    private javax.swing.JTextField txtHost;
    // End of variables declaration//GEN-END:variables
}
