/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora.gui;

import calculadora.Cliente;
import calculadora.Expressao;
import calculadora.tcp.ClienteTcp;
import calculadora.udp.ClienteUdp;
import javax.swing.JOptionPane;

/**
 *
 * @author udesc
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    Expressao tmpExpressao;
    private int valor1, valor2, operacao;
    private boolean resultado = false;
    private Cliente cliente;
    
    public Interface(String host, int tcp) {
        initComponents();
        
        if(tcp == 1){
            this.cliente = new ClienteTcp(host);
        }else{
            this.cliente = new ClienteUdp(host);
        }
    }

    
    private void defineN1(String entrada){
        valor1 = Integer.valueOf(entrada);
    }
    
    private void defineN2(String entrada){
        valor2 = Integer.valueOf(entrada);
    }
    
         private void ativarBotoes(boolean flag) {
        menos.setEnabled(flag);
        mais.setEnabled(flag);
        multiplica.setEnabled(flag);
        divide.setEnabled(flag);
    }
    
    private void erro(boolean flag) {
        zero.setEnabled(!flag);
        um.setEnabled(!flag);
        dois.setEnabled(!flag);
        tres.setEnabled(!flag);
        quatro.setEnabled(!flag);
        cinco.setEnabled(!flag);
        seis.setEnabled(!flag);
        sete.setEnabled(!flag);
        oito.setEnabled(!flag);
        nove.setEnabled(!flag);
        igual.setEnabled(!flag);
        ativarBotoes(!flag);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        igual = new javax.swing.JButton();
        nove = new javax.swing.JButton();
        um = new javax.swing.JButton();
        zero = new javax.swing.JButton();
        ver = new javax.swing.JPanel();
        visor = new javax.swing.JLabel();
        btnHistorico = new javax.swing.JButton();
        cinco = new javax.swing.JButton();
        seis = new javax.swing.JButton();
        sete = new javax.swing.JButton();
        oito = new javax.swing.JButton();
        mais = new javax.swing.JButton();
        dois = new javax.swing.JButton();
        tres = new javax.swing.JButton();
        quatro = new javax.swing.JButton();
        del = new javax.swing.JButton();
        limpa = new javax.swing.JButton();
        multiplica = new javax.swing.JButton();
        menos = new javax.swing.JButton();
        divide = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        igual.setText("=");
        igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                igualActionPerformed(evt);
            }
        });

        nove.setText("9");
        nove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noveActionPerformed(evt);
            }
        });

        um.setText("1");
        um.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                umActionPerformed(evt);
            }
        });

        zero.setText("0");
        zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroActionPerformed(evt);
            }
        });

        ver.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout verLayout = new javax.swing.GroupLayout(ver);
        ver.setLayout(verLayout);
        verLayout.setHorizontalGroup(
            verLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(visor, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        verLayout.setVerticalGroup(
            verLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(visor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        btnHistorico.setText("histórico");
        btnHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoricoActionPerformed(evt);
            }
        });

        cinco.setText("5");
        cinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cincoActionPerformed(evt);
            }
        });

        seis.setText("6");
        seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seisActionPerformed(evt);
            }
        });

        sete.setText("7");
        sete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seteActionPerformed(evt);
            }
        });

        oito.setText("8");
        oito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oitoActionPerformed(evt);
            }
        });

        mais.setText("+");
        mais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maisActionPerformed(evt);
            }
        });

        dois.setText("2");
        dois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doisActionPerformed(evt);
            }
        });

        tres.setText("3");
        tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tresActionPerformed(evt);
            }
        });

        quatro.setText("4");
        quatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quatroActionPerformed(evt);
            }
        });

        del.setText("DEL");

        limpa.setText("AC");
        limpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpaActionPerformed(evt);
            }
        });

        multiplica.setText("*");
        multiplica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicaActionPerformed(evt);
            }
        });

        menos.setText("-");
        menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosActionPerformed(evt);
            }
        });

        divide.setText("/");
        divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(um)
                            .addComponent(zero))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dois)
                                .addGap(8, 8, 8)
                                .addComponent(tres)
                                .addGap(7, 7, 7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(multiplica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(divide)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(igual))
                    .addComponent(btnHistorico)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(limpa, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(del, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(quatro)
                            .addGap(6, 6, 6)
                            .addComponent(cinco)
                            .addGap(6, 6, 6)
                            .addComponent(seis)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(menos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(sete)
                            .addGap(6, 6, 6)
                            .addComponent(oito)
                            .addGap(6, 6, 6)
                            .addComponent(nove)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(mais))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(ver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(limpa)
                    .addComponent(del))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sete)
                    .addComponent(oito)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nove)
                        .addComponent(mais)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quatro)
                    .addComponent(cinco)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(seis)
                        .addComponent(menos)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(um)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(zero)
                            .addComponent(multiplica)
                            .addComponent(divide)))
                    .addComponent(dois)
                    .addComponent(tres)
                    .addComponent(igual, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(btnHistorico)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_igualActionPerformed
        if (!mais.isEnabled()) {
            this.defineN2(this.visor.getText());
            if (valor2 == 0 && this.operacao == Expressao.DIVISAO) {
                visor.setText("Inválido");
                erro(true);
            } else {
                visor.setText("0");
                ativarBotoes(true);
                Expressao tmpExpressao = new Expressao((float)this.valor1, operacao, (float)this.valor2);
                float resultado = this.cliente.novaConta((float)this.valor1, operacao, (float)this.valor2);
                System.out.println("Resultado: "+resultado);
                visor.setText(String.valueOf(resultado));
                this.resultado = true;
            }
        }
    }//GEN-LAST:event_igualActionPerformed

    private void noveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noveActionPerformed
        String numero = visor.getText();
        if (numero.compareTo("0") == 0 || resultado == true) {
            visor.setText("9");
        } else {
            visor.setText(numero + "9");
        }
    }//GEN-LAST:event_noveActionPerformed

    private void umActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_umActionPerformed
        String numero = visor.getText();
        if (numero.compareTo("0") == 0 || resultado == true) {
            visor.setText("1");
        } else {
            visor.setText(numero + "1");
        }
        resultado = false;
    }//GEN-LAST:event_umActionPerformed

    private void zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroActionPerformed
        String numero = visor.getText();
        if (numero.compareTo("0") != 0) {
            visor.setText(numero + "0");
        }
        resultado = false;
    }//GEN-LAST:event_zeroActionPerformed

    private void btnHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoricoActionPerformed
        this.tmpExpressao = this.cliente.requisitaExpressao();
        if(this.tmpExpressao != null){
            JOptionPane.showMessageDialog(this,
            "Operandos: "+this.tmpExpressao.n1+" e "+this.tmpExpressao.n2,
            "Histórico",
            JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnHistoricoActionPerformed

    private void cincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cincoActionPerformed
        String numero = visor.getText();
        if (numero.compareTo("0") == 0 || resultado == true) {
            visor.setText("5");
        } else {
            visor.setText(numero + "5");
        }
    }//GEN-LAST:event_cincoActionPerformed

    private void seisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seisActionPerformed
        String numero = visor.getText();
        if (numero.compareTo("0") == 0 || resultado == true) {
            visor.setText("6");
        } else {
            visor.setText(numero + "6");
        }
    }//GEN-LAST:event_seisActionPerformed

    private void seteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seteActionPerformed
        String numero = visor.getText();
        if (numero.compareTo("0") == 0 || resultado == true) {
            visor.setText("7");
        } else {
            visor.setText(numero + "7");
        }
    }//GEN-LAST:event_seteActionPerformed

    private void oitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oitoActionPerformed
        String numero = visor.getText();
        if (numero.compareTo("0") == 0 || resultado == true) {
            visor.setText("8");
        } else {
            visor.setText(numero + "8");
        }
    }//GEN-LAST:event_oitoActionPerformed

    private void maisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maisActionPerformed
        this.defineN1(visor.getText());
        visor.setText("0");
        ativarBotoes(false);
        this.operacao = Expressao.SOMA;
    }//GEN-LAST:event_maisActionPerformed

    private void doisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doisActionPerformed
        String numero = visor.getText();
        if (numero.compareTo("0") == 0 || resultado == true) {
            visor.setText("2");
        } else {
            visor.setText(numero + "2");
        }
    }//GEN-LAST:event_doisActionPerformed

    private void tresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tresActionPerformed
        String numero = visor.getText();
        if (numero.compareTo("0") == 0 || resultado == true) {
            visor.setText("3");
        } else {
            visor.setText(numero + "3");
        }
    }//GEN-LAST:event_tresActionPerformed

    private void quatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quatroActionPerformed
        String numero = visor.getText();
        if (numero.compareTo("0") == 0 || resultado == true) {
            visor.setText("4");
        } else {
            visor.setText(numero + "4");
        }
    }//GEN-LAST:event_quatroActionPerformed

    private void limpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpaActionPerformed
        if (!mais.isEnabled()) {
            valor2 = 0;
            visor.setText(String.valueOf(valor2));
            erro(false);
        } else {
            valor1 = 0;
            visor.setText(String.valueOf(valor1));
            erro(false);
        }
    }//GEN-LAST:event_limpaActionPerformed

    private void multiplicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicaActionPerformed
        this.defineN1(visor.getText());
        visor.setText("0");
        ativarBotoes(false);
        this.operacao = Expressao.MULTIPLICACAO;
    }//GEN-LAST:event_multiplicaActionPerformed

    private void menosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosActionPerformed
        this.defineN1(visor.getText());
        visor.setText("0");
        ativarBotoes(false);
        this.operacao = Expressao.SUBTRACAO;
    }//GEN-LAST:event_menosActionPerformed

    private void divideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideActionPerformed
        this.defineN1(visor.getText());
        visor.setText("0");
        ativarBotoes(false);
        this.operacao = Expressao.DIVISAO;
    }//GEN-LAST:event_divideActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHistorico;
    private javax.swing.JButton cinco;
    private javax.swing.JButton del;
    private javax.swing.JButton divide;
    private javax.swing.JButton dois;
    private javax.swing.JButton igual;
    private javax.swing.JButton limpa;
    private javax.swing.JButton mais;
    private javax.swing.JButton menos;
    private javax.swing.JButton multiplica;
    private javax.swing.JButton nove;
    private javax.swing.JButton oito;
    private javax.swing.JButton quatro;
    private javax.swing.JButton seis;
    private javax.swing.JButton sete;
    private javax.swing.JButton tres;
    private javax.swing.JButton um;
    private javax.swing.JPanel ver;
    private javax.swing.JLabel visor;
    private javax.swing.JButton zero;
    // End of variables declaration//GEN-END:variables
}
